### ISSUE TITLE
CLI command returns an error

### ISSUE THREAD

**Issue by p380** [georgringer/faker#10]
When I run the command returns the error below.

Command:
bin/typo3 faker:execute --table fe_users --pid 393 --amount 20

error:
The "--table" option does not exist.
 
environment:
TYPO3 10 LTS

**Comment by baschny** [comment]
@p380 good catch, this is just a bug in the README. We switched to using a Symfony Cmd Controller and in this cases the arguments do not require this kind of syntax. So you should run simply:

```
bin/typo3 faker:execute fe_users 393 20
```

I fixed that in the README in #11. Please give a short feedback if that worked for you and we merge it.

**Comment by p380** [comment]
> @p380 good catch, this is just a bug in the README. We switched to using a Symfony Cmd Controller and in this cases the arguments do not require this kind of syntax. So you should run simply:
> 
> ```
> bin/typo3 faker:execute fe_users 393 20
> ```
> 
> I fixed that in the README in #11. Please give a short feedback if that worked for you and we merge it.

Thanx. It's working.
